//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoSleep.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoSleep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrayIcon {
            get {
                object obj = ResourceManager.GetObject("TrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrayIconInactive {
            get {
                object obj = ResourceManager.GetObject("TrayIconInactive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>Tray menu: Close</summary>
        internal static string TrayMenu_Close {
            get { return ResourceManager.GetString("TrayMenu_Close", resourceCulture); }
        }

        /// <summary>Tray menu: Autostart at login</summary>
        internal static string TrayMenu_Autostart {
            get { return ResourceManager.GetString("TrayMenu_Autostart", resourceCulture); }
        }

        /// <summary>Tray menu: Remember enabled state</summary>
        internal static string TrayMenu_RememberState {
            get { return ResourceManager.GetString("TrayMenu_RememberState", resourceCulture); }
        }

        /// <summary>Tray menu: Configure apps to monitor</summary>
        internal static string TrayMenu_ConfigureApps {
            get { return ResourceManager.GetString("TrayMenu_ConfigureApps", resourceCulture); }
        }

        /// <summary>Tray menu: Enabled</summary>
        internal static string TrayMenu_Enabled {
            get { return ResourceManager.GetString("TrayMenu_Enabled", resourceCulture); }
        }

        /// <summary>Tray menu: Keep screen on</summary>
        internal static string TrayMenu_KeepScreenOn {
            get { return ResourceManager.GetString("TrayMenu_KeepScreenOn", resourceCulture); }
        }

        /// <summary>Tooltip: Should we start when you log in?</summary>
        internal static string Tooltip_Autostart {
            get { return ResourceManager.GetString("Tooltip_Autostart", resourceCulture); }
        }

        /// <summary>Tooltip: Should we remember the enabled state between restarts?</summary>
        internal static string Tooltip_RememberState {
            get { return ResourceManager.GetString("Tooltip_RememberState", resourceCulture); }
        }

        /// <summary>Tooltip: Configure apps to keep the screen on when they are running.</summary>
        internal static string Tooltip_ConfigureApps {
            get { return ResourceManager.GetString("Tooltip_ConfigureApps", resourceCulture); }
        }

        /// <summary>Tooltip: Are we enabled right now?</summary>
        internal static string Tooltip_Enabled {
            get { return ResourceManager.GetString("Tooltip_Enabled", resourceCulture); }
        }

        /// <summary>Tooltip: If display should be kept always on in addition to keeping the system on.</summary>
        internal static string Tooltip_KeepScreenOn {
            get { return ResourceManager.GetString("Tooltip_KeepScreenOn", resourceCulture); }
        }

        /// <summary>Message: {0} instance is already running.</summary>
        internal static string Msg_InstanceRunning {
            get { return ResourceManager.GetString("Msg_InstanceRunning", resourceCulture); }
        }

        /// <summary>Message: Wasn't able to remove autostart shortcut from '{0}'. Error: {1}</summary>
        internal static string Msg_AutostartRemoveFailed {
            get { return ResourceManager.GetString("Msg_AutostartRemoveFailed", resourceCulture); }
        }

        /// <summary>Message: Wasn't able to create autostart shortcut at '{0}'. Error: {1}</summary>
        internal static string Msg_AutostartCreateFailed {
            get { return ResourceManager.GetString("Msg_AutostartCreateFailed", resourceCulture); }
        }

        /// <summary>Button: Apps watching is enabled</summary>
        internal static string Btn_AppsWatchingEnabled {
            get { return ResourceManager.GetString("Btn_AppsWatchingEnabled", resourceCulture); }
        }

        /// <summary>Button: Apps watching is DISABLED</summary>
        internal static string Btn_AppsWatchingDisabled {
            get { return ResourceManager.GetString("Btn_AppsWatchingDisabled", resourceCulture); }
        }

        /// <summary>File dialog filter label: Executable</summary>
        internal static string FileDlg_FilterExecutable {
            get { return ResourceManager.GetString("FileDlg_FilterExecutable", resourceCulture); }
        }

        /// <summary>File dialog filter label: All files</summary>
        internal static string FileDlg_FilterAllFiles {
            get { return ResourceManager.GetString("FileDlg_FilterAllFiles", resourceCulture); }
        }

        /// <summary>File dialog title: Select application executable</summary>
        internal static string FileDlg_Title {
            get { return ResourceManager.GetString("FileDlg_Title", resourceCulture); }
        }

        /// <summary>Column header: Name</summary>
        internal static string Col_Name {
            get { return ResourceManager.GetString("Col_Name", resourceCulture); }
        }

        /// <summary>Column header: Exe Path</summary>
        internal static string Col_ExePath {
            get { return ResourceManager.GetString("Col_ExePath", resourceCulture); }
        }

        /// <summary>Button: Add</summary>
        internal static string Btn_Add {
            get { return ResourceManager.GetString("Btn_Add", resourceCulture); }
        }

        /// <summary>Button: Remove</summary>
        internal static string Btn_Remove {
            get { return ResourceManager.GetString("Btn_Remove", resourceCulture); }
        }

        /// <summary>Button: Enable</summary>
        internal static string Btn_Enable {
            get { return ResourceManager.GetString("Btn_Enable", resourceCulture); }
        }

        /// <summary>Button: Close</summary>
        internal static string Btn_Close {
            get { return ResourceManager.GetString("Btn_Close", resourceCulture); }
        }

        /// <summary>Form title: Configure Applications to monitor</summary>
        internal static string Form_Title {
            get { return ResourceManager.GetString("Form_Title", resourceCulture); }
        }
    }
}
